# Generated by Django 5.0.2 on 2025-04-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaglobine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='anaglobine_patient',
        ),
    ]
