# Generated by Django 5.0.2 on 2025-05-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaglobine', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratoire',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='adresse',
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.CreateModel(
            name='CreneauDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_reserve', models.BooleanField(default=False)),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='anaglobine.laboratoire')),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='anaglobine.typeanalyse')),
            ],
            options={
                'unique_together': {('laboratoire', 'type_analyse', 'date', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='non_lu', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='anaglobine.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionniste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaglobine.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=10)),
                ('creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaglobine.creneaudisponible')),
                ('laboratoire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaglobine.laboratoire')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='anaglobine.patient')),
                ('type_analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaglobine.typeanalyse')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('en_ligne', 'En ligne')], max_length=20)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anaglobine.rendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='resultats/')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anaglobine.laboratoire')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anaglobine.patient')),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anaglobine.rendezvous')),
            ],
            options={
                'unique_together': {('rendezvous',)},
            },
        ),
        migrations.CreateModel(
            name='AnalyseLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_disponibles', to='anaglobine.laboratoire')),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratoires_disponibles', to='anaglobine.typeanalyse')),
            ],
            options={
                'unique_together': {('laboratoire', 'type_analyse')},
            },
        ),
    ]
