# Generated by Django 5.0.2 on 2025-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaglobine', '0003_typeanalyse_remove_laboratoire_disponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatanalyse',
            name='fichier_pdf',
            field=models.BinaryField(),
        ),
    ]
