# Generated by Django 5.0.2 on 2025-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaglobine', '0004_alter_resultatanalyse_fichier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
